### PR TITLE
252

### PR DESCRIPTION
**Pull request by mattdehring**
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/253)

### CODE REVIEW

**Comment by keilw** [comment]
Thanks, but @mattdehring can you tell us, if you joined the JCP already?

**Comment by mattdehring** [comment]
I have not joined the JCP.

**Comment by keilw** [comment]
Sorry to hear. We could make an exception for a small change (as on one occasion e.g. a PR by @Azbesciak) but more frequent PRs should come from contributors who are OK to join as Associate JCP members. I asked @andi-huber to review.

**Comment by mattdehring** [comment]
I am applying to be an associate JCP member.

**Comment by keilw** [comment]
Thanks, I trust (maybe after Oracle Code One;-) it'll be approved and either @andi-huber or I shall review the PR and merge if it's fine. Thanks for taking your time to join the JCP. You can actually vote from Nov 5 in the "Associate" category if you want: https://jcp.org/en/whatsnew/elections

**Pull request merged**
