### PR TITLE
adds support for relative quantity multiplication

### PR DESCRIPTION
**Pull request by andi-huber**
solves  #247

implemented according to https://github.com/unitsofmeasurement/unit-api/wiki/Arithmetic-rules-for-Difference-versus-Absolute-quantities

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/290)

### CODE REVIEW

**Comment by keilw** [comment]
@andi-huber Unfortunately you introduced a bug here because Optional.isEmpty() did not exist before Java 9 ;-/ I moved the latest version of AbstractConverter, AbstractQuantity and others to the jdk9 multi-release codebase, if you find a way to backport it to Java 8 please to. I have not explored any multi-release tests, therefore no JUnit tests for Java 9 or 14 specific features.

**Comment by andi-huber** [comment]
Uups sorry for that. I should be able to do a new revision next week.

**Comment by keilw** [comment]
Yeah it's worse, it was introduced in Java 11, so have to isolate the changes into the Java 12 release codebase. I don't know why the heck they even bothered with that `isEmpty()`, you should be able to fix it by using `!isPresent()` ;-)

**Comment by keilw** [comment]
It's much worse, Maven constantly crashes with an OutOfMemoryError and there is no way to solve that, even putting Xmx and similar to 3GB fails, it seems mostly a problem of Surefire, but that gets worse with multiple release JARs, it looks like the worst failure takes place in the Java 12 code.

**Comment by andi-huber** [comment]
How do I verify on my end, that the maven multi jar build works. Do I just call
`mvn clean install`
or anything else?

**Comment by andi-huber** [comment]
Doing `mvn clean install` I'm getting 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain (default) on project indriya: Cannot find matching toolchain definitions for the following toolchain types:
[ERROR] jdk [ version='[8,)' ]
[ERROR] Please make sure you define the required toolchains in your ~/.m2/toolchains.xml file.
```
Which suggests there is something missing in my local `~/.m2/toolchains.xml`

**Comment by andi-huber** [comment]
Ok, all I needed to know seems to be defined in `.circleci/config.yml`. Think I understund how to do a multi jar build now locally.

**Comment by keilw** [comment]
Cool, if you use Toolchain, also don't forget to include that.
I came across a strange behavior and created a tiny example project, maybe won't share it on the uom organization but at least in Eclipse it almost feels like in a Java 12 project with true "multi release" JAR feature (meaning more than just 2) accidentally picks only the META-INF/versions/14 instead of 12, at least that's what I see in Eclipse. I did that without Maven in Eclipse or IntelliJ only, the behavior is the same, the Java 12 class `NumberFormatStyle` is not found although it's in the JAR.

**Pull request merged**
