### PR TITLE
Changed internal addition for LongQuantity to use BigDecimal instead …

### PR DESCRIPTION
**Pull request by filipvanlaenen**
…of Double, such that it keeps full precision close to the range boundaries.

Unit tests have been corrected too.

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/40)

### CODE REVIEW

**Comment by keilw** [comment]
What is the reason for `BigDecimal` instead of `BigInteger` in `add`?

**Comment by filipvanlaenen** [comment]
In the case of 1 Ω + 1 mΩ, I need to be able to see that when I try to do the addition using Ω, the result is 1.001, which has a fraction, and that I should use mΩ instead. If you use BigInteger, you would only get 1, and the result of the addition would become 1 Ω, not 1,001 mΩ. This case is covered by the unit test LongQuantityTest.additionWithSmallerMultipleCastsToSmallerMultipleIfNeeded.

**Comment by keilw** [comment]
As long as the result is not something that would exceed the `Long` type, it seems fine to use `BigDecimal` or (where applicable) `BigInteger` under Java SE 8+. If it did, then there would be little point in having multiple Quantity implementations.

**Comment by keilw** [comment]
What happened? Will you propose another PR later?

**Comment by filipvanlaenen** [comment]
No, I thought you had merged in, not just approved, and therefore I started to clean up in my fork. I restored the branch, but it looks like the pull request is still closed.

(I'm still learning how to send in pull requests properly, sorry for that.)

**Comment by keilw** [comment]
No, approved (I put myself as the only reviewer) just means one or more reviewers approve it to be merged later.

**Comment by keilw** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unitsofmeasurement/indriya/40)*

**Pull request merged**
