### PR TITLE
235: add maven profile 'm2e' that activates on eclipse

### LINKED ISSUE #235: Ri checkout failes to build or test using eclipse

### PR DESCRIPTION
**Pull request by andi-huber**
- to specifically fix eclipse build and test issues

fixes #235

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/236)

### CODE REVIEW

**Comment by andi-huber** [comment]
I'd be surprised if this change breaks the maven build. (However, unless really tested we can't be sure.)

**Comment by andi-huber** [comment]
Its a profile that only activates when m2e is present, which is the name of the maven integration for eclipse. Its specifically meant to fix build issues when checking out with eclipse and then also build with eclipse's own java compiler and later test with eclipse's Junit 5 integration. The resulting build is not meant as a release build. 

So we could rename the profile to 'eclipse' if you prefer, but I'd not recommend the generic 'java8' name for this particular profile.

**Comment by andi-huber** [comment]
... this profile should not even be required, but unfortunately 'm2e' does still require a workaround and the Jupiter integration of eclipse requires depends on newer junit versions that the official RI build.

**Comment by keilw** [comment]
So when you run it in the commandline it works without that profile?

**Pull request merged**
