### PR TITLE
Use Number instead of Long to represent values in temporal Quantities.

### PR DESCRIPTION
**Pull request by andi-huber**
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/227)

### CODE REVIEW

**Comment by andi-huber** [comment]
part of #220
Further simplifies Temporal Quantity implementations.

**Comment by andi-huber** [comment]
Would be `@since 2.0` OK for `TimeUnitQuantity.getValue()`?

**Comment by keilw** [comment]
It depends because `getValue()` was always there, maybe to avoid confusion leave it as 1.0 for the existence. Broadening it to `Number `changes nothing on the outside.

**Comment by andi-huber** [comment]
Thx. I've updated this PR accordingly.

**Pull request merged**
