### PR TITLE
[WIP] 117: added widening for numeric multiplication/division

### PR DESCRIPTION
**Pull request by thodorisbais**
@keilw  I'm not sure if this is what we want, so, I would be interested in your feedback.

Besides the (minor) format changes, what actually changed is [here](https://github.com/unitsofmeasurement/indriya/compare/master...thodorisbais:117-widen-numeric-quantities-for-multiplication-and-division?expand=1#diff-33b15b88ea918c328f88e6791f639db2R204) and [here](https://github.com/unitsofmeasurement/indriya/compare/master...thodorisbais:117-widen-numeric-quantities-for-multiplication-and-division?expand=1#diff-33b15b88ea918c328f88e6791f639db2R212)

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/191)

### CODE REVIEW

**Comment by thodorisbais** [comment]
@keilw any view here?

**Comment by keilw** [comment]
@thodorisbais Thanks, I asked 3 others for review to get a second opinion, hope at least one of them can have a look at it.

**Comment by desruisseaux** [comment]
The diff seems to contain replacements of whitespace by tabulations. I'm neutral on what policy indriya wants to choose, but the project should probably stick to an uniform policy. I tend to prefer spaces over tabulations because the later depends on IDE settings.

On more fundamental aspect, I do not have a broad picture of where methods like `canWidenTo` are used (I'm not familiar with Indriya architecture, and the Seshat implementation uses only the `double` primitive type, so the type widening question does not apply to it), so I can not provide useful advise here.

**Comment by keilw** [comment]
Thanks for the input on areas you can provide @desruisseaux, we already have an `.editorconfig`, but it currently says "tab", feel free to adjust where necessary.

**Comment by thodorisbais** [comment]
@desruisseaux there might be indeed some inconsistencies here and there and this is one of the reasons we still keep [this](https://github.com/unitsofmeasurement/unit-api/issues/162) one as a placeholder; I think IntelliJ format should be the one to be used globally in our project (that's why I try conforming each file I touch to IntelliJ's format), but still, it needs further investigation.

On topic, given that @desruisseaux is neutral here, what do the rest think? @dautelle ? @filipvanlaenen ? Did you have any chance to take a look at this?

**Pull request merged**
