### PR TITLE
allow new instances of SimpleUnitFormat to be created

### PR DESCRIPTION
**Pull request by andi-huber**
Issue #344.

Is expected to resolve https://github.com/geotools/geotools/pull/3232.

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/345)

### CODE REVIEW

**Review by keilw — COMMENTED** [review]
@andi-huber It has a merge conflict, if you can resolve that, please go ahead, I believe you should be able to merge.

**Review by keilw — CHANGES_REQUESTED** [review]
@andi-huber At second thought, sorry why rename it, and this would be ignored by 90% of all existing calls, making it confusing.
What's the difference in the existing method, I trust you won't rename it because it would break all users in different modules?

If this one always discards a cached instance, why not add an extra argument to `getInstance(Flavor)` like a `boolean ` flag kind of like "refresh" or "newInstance" etc. so the default behavior would keep a cache like it does now and adding this flag would discard it, how does that sound?
Should always recreating it not be too much of a performance issue, then it could be considered but there is no real need to create a new instance every single time because not a lot changes.
Plus make `initDefault private` if possible, I assume this method call will be sufficient and no explicit call of init.,.. is needed from the outside?

Or what about skipping the get and just call it `newInstance()` along the lines of the Java Reflection methods? ;-)

**Review by keilw — COMMENTED** [review]
@andi-huber See https://github.com/unitsofmeasurement/indriya/issues/344 comments, please leave the name, it fits a pattern of many java.text.Format subclasses but ensure the JavaDoc is clear about what each of them does.

**Review by keilw — APPROVED** [review]
@andi-huber See https://github.com/unitsofmeasurement/indriya/issues/344 comments, please leave the name, it fits a pattern of many java.text.Format subclasses but ensure the JavaDoc is clear about what each of them does.

**Comment by keilw** [comment]
Great, @andi-huber is it safe to delete that branch as recommended here?

**Comment by andi-huber** [comment]
I got rid of these static initializers by moving around some code blocks and fields. Not changing any behavior (hopefully).

**Pull request merged**
