### PR TITLE
Introduces UnitFormatRountripTest, to test any UnitFormat

### PR DESCRIPTION
**Pull request by andi-huber**
also disabling tests that fail yet
also add junit-jupiter-params to pom.xml (test-scope)

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/153)

### CODE REVIEW

**Comment by keilw** [comment]
@andi-huber Thanks, I don't think it's this PR, but the `FunctionalInterface UnitCompositionHandler` should go into the function package of Indriya. Will fix that now, please remember for further cases if they came up. The underscores look slightly strange, even for a package local class. Let's keep an eye on Codacy. If it's flagged there, maybe it would be an option to change them to inner classes of `CompositionTask`?

**Comment by andi-huber** [comment]
Ok, thanks Werner! 
I'm working on a new PR with some fixes regarding UnitFormat testing. 
I'm happy to rename the underscore class names. (We use this naming scheme in Apache Isis for 'mixins'; got pretty used to it by now).

**Comment by keilw** [comment]
Ok. As long as the code checks don't flag ist, there's no real problem. If you raise new PRs, would you consider changing the name of the functional interface? `UnitCompositionHandler` seems to only deal with `UnitConverter` implementations, not `Unit` implementations. I understand `UnitConverterCompositionHandler` and some extra prefix in implementing classes could get awfully long. How would `ConverterCompositionHandler` sound? In the `function` package there are also concrete converters (no harm, they deal with conversion "functions" anyway) like `AddConverter` where the "unit" word is skipped for briefness.

**Comment by andi-huber** [comment]
Sure, I can change the name of `UnitCompositionHandler` -> `ConverterCompositionHandler`. Good Idea!

**Comment by keilw** [comment]
Sure please do, thanks. I had to add a cleanup line in `SimpleFormatTest` (I don't recall if JUnit 5 has an `@after` section for particular tests only?) because its "temporary" relabeling of CANDELA to uppercase had side-effects on other tests. And the order of JUnit tests is still not guaranteed (unless you enforce it somehow, but I would not do this to every single unit test here)

**Pull request merged**
