### PR TITLE
#124: fix handling of powered units (creation and simple formatting)

### PR DESCRIPTION
**Pull request by DrDaleks**
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/indriya/129)

### CODE REVIEW

**Comment by keilw** [comment]
Somehow it broke the build;-/ Will see why

**Comment by keilw** [comment]
It was a test based on an old assumption/formatting. Would be great it it was possible to also change such tests to pass with a PR, I fixed it this time already.

**Comment by DrDaleks** [comment]
My bad. Will definitely do next time!

**Comment by keilw** [comment]
Thanks, does it solve https://github.com/unitsofmeasurement/indriya/issues/124 or is anything left to do?

**Comment by keilw** [comment]
If you want please do. The P1 bug is good to be resolved before the EDR, other details can be improved and refined before Public Review or Proposed Final Draft which are the next phases of the JSR down the road.

Thanks.

**Comment by keilw** [comment]
If you consider JCP Associate Membership, we'd also be happy to list you as Contributor to JSR 385.

**Pull request merged**
